version: '3.7'
services:
    simulator:
        image: carla_simulator_1:v1
        logging:
          options:
            max-size: "10m"
            max-file: "3"
        privileged: true
        environment:
            SDL_VIDEODRIVER: x11
            DISPLAY: $DISPLAY
        ports:
            - "2000:2000"
            - "2001:2001"
            - "2002:2002"

        runtime: nvidia
        command: ./CarlaUE4.sh  -quality-level=Low -carla-rpc-port=2000
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /etc/localtime:/etc/localtime
            - /etc/timezone:/etc/timezone
        restart: always
